telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:\projects\lesson1\tg_bot.py", line 30, in talk_to_me
    user_text[1000000000000]
IndexError: string index out of range
